# Generated by Django 3.2 on 2025-04-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('sensorsId', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField(default=4)),
                ('humidity', models.FloatField(default=4)),
                ('air_quality', models.FloatField(default=4)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
